import {SUBSCRIPTION_STATUS} from "@bikairproject/shared";

export const SubscriptionValues: string[] = [
    SUBSCRIPTION_STATUS.ACTIVE,
    SUBSCRIPTION_STATUS.ON_HOLD,
    SUBSCRIPTION_STATUS.UNPAID,
    SUBSCRIPTION_STATUS.CANCELED,
    SUBSCRIPTION_STATUS.EXPIRED,
    SUBSCRIPTION_STATUS.INCOMPLETE,
];
