import {TRIP_STATUS,TripStatusType} from "@bikairproject/shared";

export const TripStatusValues: TripStatusType[] = [
    TRIP_STATUS.STARTING,
    TRIP_STATUS.OPEN,
    TRIP_STATUS.CANCEL,
    TRIP_STATUS.PAYMENT_SUCCESS,
    TRIP_STATUS.PAYMENT_HOLD_CONFIRM,
    TRIP_STATUS.CLOSED,
    TRIP_STATUS.PAYMENT_INV_CREATED,
    TRIP_STATUS.FAILED,
    TRIP_STATUS.FAILED_AT_END,
    TRIP_STATUS.FAILED_AT_START,
    TRIP_STATUS.PAYMENT_IN_PROGRESS,
    TRIP_STATUS.FREE_TRIP,
    TRIP_STATUS.WAIT_VALIDATION
];
